// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package aws

import (
	models "github.com/xinsnake/databricks-sdk-golang/aws/models"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClustersAPI) DeepCopyInto(out *ClustersAPI) {
	*out = *in
	in.Client.DeepCopyInto(&out.Client)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClustersAPI.
func (in *ClustersAPI) DeepCopy() *ClustersAPI {
	if in == nil {
		return nil
	}
	out := new(ClustersAPI)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClustersEventsResponse) DeepCopyInto(out *ClustersEventsResponse) {
	*out = *in
	if in.Events != nil {
		in, out := &in.Events, &out.Events
		*out = make([]models.ClusterEvent, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.NextPage = in.NextPage
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClustersEventsResponse.
func (in *ClustersEventsResponse) DeepCopy() *ClustersEventsResponse {
	if in == nil {
		return nil
	}
	out := new(ClustersEventsResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClustersListZonesResponse) DeepCopyInto(out *ClustersListZonesResponse) {
	*out = *in
	if in.Zones != nil {
		in, out := &in.Zones, &out.Zones
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClustersListZonesResponse.
func (in *ClustersListZonesResponse) DeepCopy() *ClustersListZonesResponse {
	if in == nil {
		return nil
	}
	out := new(ClustersListZonesResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DBClient) DeepCopyInto(out *DBClient) {
	*out = *in
	in.Option.DeepCopyInto(&out.Option)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DBClient.
func (in *DBClient) DeepCopy() *DBClient {
	if in == nil {
		return nil
	}
	out := new(DBClient)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DbfsAPI) DeepCopyInto(out *DbfsAPI) {
	*out = *in
	in.Client.DeepCopyInto(&out.Client)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DbfsAPI.
func (in *DbfsAPI) DeepCopy() *DbfsAPI {
	if in == nil {
		return nil
	}
	out := new(DbfsAPI)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DbfsCreateResponse) DeepCopyInto(out *DbfsCreateResponse) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DbfsCreateResponse.
func (in *DbfsCreateResponse) DeepCopy() *DbfsCreateResponse {
	if in == nil {
		return nil
	}
	out := new(DbfsCreateResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DbfsListResponse) DeepCopyInto(out *DbfsListResponse) {
	*out = *in
	if in.Files != nil {
		in, out := &in.Files, &out.Files
		*out = make([]models.FileInfo, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DbfsListResponse.
func (in *DbfsListResponse) DeepCopy() *DbfsListResponse {
	if in == nil {
		return nil
	}
	out := new(DbfsListResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DbfsReadResponse) DeepCopyInto(out *DbfsReadResponse) {
	*out = *in
	if in.Data != nil {
		in, out := &in.Data, &out.Data
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DbfsReadResponse.
func (in *DbfsReadResponse) DeepCopy() *DbfsReadResponse {
	if in == nil {
		return nil
	}
	out := new(DbfsReadResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GroupsAPI) DeepCopyInto(out *GroupsAPI) {
	*out = *in
	in.Client.DeepCopyInto(&out.Client)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GroupsAPI.
func (in *GroupsAPI) DeepCopy() *GroupsAPI {
	if in == nil {
		return nil
	}
	out := new(GroupsAPI)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GroupsCreateResponse) DeepCopyInto(out *GroupsCreateResponse) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GroupsCreateResponse.
func (in *GroupsCreateResponse) DeepCopy() *GroupsCreateResponse {
	if in == nil {
		return nil
	}
	out := new(GroupsCreateResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceProfilesAPI) DeepCopyInto(out *InstanceProfilesAPI) {
	*out = *in
	in.Client.DeepCopyInto(&out.Client)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceProfilesAPI.
func (in *InstanceProfilesAPI) DeepCopy() *InstanceProfilesAPI {
	if in == nil {
		return nil
	}
	out := new(InstanceProfilesAPI)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JobsAPI) DeepCopyInto(out *JobsAPI) {
	*out = *in
	in.Client.DeepCopyInto(&out.Client)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JobsAPI.
func (in *JobsAPI) DeepCopy() *JobsAPI {
	if in == nil {
		return nil
	}
	out := new(JobsAPI)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JobsRunsGetOutputResponse) DeepCopyInto(out *JobsRunsGetOutputResponse) {
	*out = *in
	out.NotebookOutput = in.NotebookOutput
	in.Metadata.DeepCopyInto(&out.Metadata)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JobsRunsGetOutputResponse.
func (in *JobsRunsGetOutputResponse) DeepCopy() *JobsRunsGetOutputResponse {
	if in == nil {
		return nil
	}
	out := new(JobsRunsGetOutputResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JobsRunsListResponse) DeepCopyInto(out *JobsRunsListResponse) {
	*out = *in
	if in.Runs != nil {
		in, out := &in.Runs, &out.Runs
		*out = make([]models.Run, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JobsRunsListResponse.
func (in *JobsRunsListResponse) DeepCopy() *JobsRunsListResponse {
	if in == nil {
		return nil
	}
	out := new(JobsRunsListResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LibrariesAPI) DeepCopyInto(out *LibrariesAPI) {
	*out = *in
	in.Client.DeepCopyInto(&out.Client)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LibrariesAPI.
func (in *LibrariesAPI) DeepCopy() *LibrariesAPI {
	if in == nil {
		return nil
	}
	out := new(LibrariesAPI)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LibrariesClusterStatusResponse) DeepCopyInto(out *LibrariesClusterStatusResponse) {
	*out = *in
	if in.LibraryStatuses != nil {
		in, out := &in.LibraryStatuses, &out.LibraryStatuses
		*out = make([]models.LibraryFullStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LibrariesClusterStatusResponse.
func (in *LibrariesClusterStatusResponse) DeepCopy() *LibrariesClusterStatusResponse {
	if in == nil {
		return nil
	}
	out := new(LibrariesClusterStatusResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScimAPI) DeepCopyInto(out *ScimAPI) {
	*out = *in
	in.Client.DeepCopyInto(&out.Client)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScimAPI.
func (in *ScimAPI) DeepCopy() *ScimAPI {
	if in == nil {
		return nil
	}
	out := new(ScimAPI)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretsAPI) DeepCopyInto(out *SecretsAPI) {
	*out = *in
	in.Client.DeepCopyInto(&out.Client)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretsAPI.
func (in *SecretsAPI) DeepCopy() *SecretsAPI {
	if in == nil {
		return nil
	}
	out := new(SecretsAPI)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TokenAPI) DeepCopyInto(out *TokenAPI) {
	*out = *in
	in.Client.DeepCopyInto(&out.Client)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TokenAPI.
func (in *TokenAPI) DeepCopy() *TokenAPI {
	if in == nil {
		return nil
	}
	out := new(TokenAPI)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TokenCreateResponse) DeepCopyInto(out *TokenCreateResponse) {
	*out = *in
	out.TokenInfo = in.TokenInfo
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TokenCreateResponse.
func (in *TokenCreateResponse) DeepCopy() *TokenCreateResponse {
	if in == nil {
		return nil
	}
	out := new(TokenCreateResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkspaceAPI) DeepCopyInto(out *WorkspaceAPI) {
	*out = *in
	in.Client.DeepCopyInto(&out.Client)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkspaceAPI.
func (in *WorkspaceAPI) DeepCopy() *WorkspaceAPI {
	if in == nil {
		return nil
	}
	out := new(WorkspaceAPI)
	in.DeepCopyInto(out)
	return out
}
